const mongoose = require("mongoose");

const quizSchema = new mongoose.Schema(
  {
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
    },
    pdf: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "PDF",
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    description: {
      type: String,
      trim: true,
    },
    // Metadata
    category: { type: String },
    tags: [{ type: String }],
    status: {
      type: String,
      enum: ["Draft", "Active", "Archived"],
      default: "Active",
    },
    version: { type: Number, default: 1 },

    settings: {
      numQuestions: { type: Number, default: 10, min: 5, max: 30 },
      difficulty: {
        type: String,
        enum: ["Easy", "Medium", "Hard", "Mixed"],
        default: "Mixed",
      },
      questionTypes: [
        {
          type: String,
          enum: ["MCQ", "TrueFalse", "FillBlank", "ShortAnswer"],
          default: "MCQ",
        },
      ],
      timeLimit: { type: Number, default: 0 }, // in seconds
      perQuestionTime: { type: Number, default: 0 },
      mode: { type: String, enum: ["Practice", "Exam"], default: "Practice" },
      markingScheme: {
        type: String,
        enum: ["normal", "negative"],
        default: "normal",
      },
    },

    // Questions generated by Gemini
    questions: [
      {
        type: {
          type: String,
          enum: ["MCQ", "TrueFalse", "FillBlank", "ShortAnswer"],
          required: true,
        },
        questionText: { type: String, required: true },
        options: [{ type: String }], // for MCQ
        correctAnswer: { type: String, required: true },
        explanation: { type: String },
      },
    ],
  },
  { timestamps: true }
);

module.exports = mongoose.model("Quiz", quizSchema);
